version: '3.1'

services:

  auth-db:
    container_name: auth-db
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: auth-db

  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
      