version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=lotto-db
    volumes:
      - lotto-data:/var/lib/postgresql/data
  lotto-service:
    image: lotto-img
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - STAGE=dev
      - BASE_URL=lotto
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DATABASE=lotto-db
      - POSTGRES_AUTO_SYNC_ENTITY=true


volumes:
  lotto-data:
