name: Push to DockerHub and Update K8s Deployment

run-name: ${{ github.actor }} is deploying this app 🚀
on:
  push:
    branches: [develop]

env:
  NEW_TAG_IMAGE: latest

jobs:
  push_to_registry:
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    env:
      NEW_TAG: ${{ github.sha }}
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.NEW_TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.NEW_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Get new Docker tag image
        run: echo ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.NEW_TAG }}

  deploy_to_k8s:
    name: Deploy Image to K8s Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create K8S Config
        env:
          KUBECTL_CONFIG_CONTENT: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECTL_CONFIG_CONTENT" > ~/.kube/config

      - name: Get Current Cluster
        run: kubectl config current-context

      - name: Check yq Version
        run: yq --version

      - name: Define Image New Version
        run: |
          echo "image_with_new_tag=${{ secrets.DOCKER_USERNAME }}/tcc-service-a:${{ env.NEW_TAG_IMAGE }}" >> $GITHUB_ENV
          echo $image_with_new_tag

      - name: Update Image in Deployment K8s
        run: yq -i '.spec.template.spec.containers[0].image=strenv(image_with_new_tag)' ./manifest/dev/deployment.yaml

      - name: Display yaml file
        run: cat ./manifest/dev/deployment.yaml

      - name: Deploy Docker image New Version to K8s cluster
        run: kubectl apply -f ./manifest/dev/. -n group-3-dev